var assert = require('assert');
const Logica = require( "../src/server/Logica.js" )


describe('Guardar medición en DDBB', function () {
  // ....................................................
  // ....................................................
  var laLogica = null
  // ....................................................
  // ....................................................
  it( "conectar a la BBDD", function() {
    laLogica = new Logica("mongodb+srv://cristianbm91:xaiPHQgaFgRzjrh1@pbiometria.foov4fh.mongodb.net/?retryWrites=true&w=majority")
  })
  // ....................................................
  // ....................................................
  it( "Borrar todas la mediciones", function() {
    laLogica.borrarTodasLasMediciones()
  })
  // ....................................................
  // ....................................................
  it( "cerrar conexión con la BBDD", async function() {
    laLogica.cerrarConexion()
  }) // it
}) // describe
describe('Guardar medición en DDBB', function () {
// ....................................................
// ....................................................
var laLogica = null
// ....................................................
// ....................................................
it( "conectar a la BBDD", function() {
  laLogica = new Logica("mongodb+srv://cristianbm91:xaiPHQgaFgRzjrh1@pbiometria.foov4fh.mongodb.net/?retryWrites=true&w=majority")
})
// ....................................................
// ....................................................
it( "guardar una medición en la BBDD", async function() {
  Medicion = {ozono: 500, temperatura: 20, geopunto: {lat: 40.416775, lon: -3.703790}}
  await laLogica.guardarMedicion(Medicion)
}) // it
// ....................................................
// ....................................................
it( "cerrar conexión con la BBDD", async function() {
  laLogica.cerrarConexion()
}) // it
}) // describe

describe('Leer medición en DDBB', function () {
// ....................................................
// ....................................................
var laLogica = null
// ....................................................
// ....................................................
it( "conectar a la BBDD", function() {
  laLogica = new Logica("mongodb+srv://cristianbm91:xaiPHQgaFgRzjrh1@pbiometria.foov4fh.mongodb.net/?retryWrites=true&w=majority")
})
// ....................................................
// ....................................................
it( "leer última medición en la BBDD", async function() {
  var res = await laLogica.leerUltimaMedicion()
  assert.equal( res[0].valorOzono, 500, "¿no es 500?")
}) // it
// ....................................................
// ....................................................
it( "cerrar conexión con la BBDD", async function() {
  laLogica.cerrarConexion()
}) // it
}) // describe
